name: CI Pipeline

on:
  push:
    branches:
      - develop
      - feature/*
      - release/*
  pull_request:
    branches:
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run React tests (Frontend)
      - name: Run frontend tests
        run: npm run test -- --coverage

      # Step 5: Run linting (Frontend and Backend)
      - name: Run linting
        run: npm run lint

      # Step 6: Run Prettier formatting check (Frontend and Backend)
      - name: Run formatting check
        run: npm run format --check

  # Step 7: Deploy to Vercel
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Vercel CLI
        run: |
          curl -fsSL https://vercel.com/download -o vercel-cli.tar.gz
          tar -xvzf vercel-cli.tar.gz
          sudo mv vercel /usr/local/bin/

      - name: Deploy to Vercel
        run: |
          vercel login ${{ secrets.VERCEL_EMAIL }}
          vercel --prod --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
